spring:
  mvc:
    servlet:
      load-on-startup: 1
    view:
      prefix: /
      suffix: .html
  task:
    scheduling:
      thread-name-prefix: "user-name-"
      pool:
        size: 3
logging:
  level:
    root: debug
server:
  tomcat:
    max-threads: 1